const plans = [
  {
    name: 'Tester',
    price: '$9',
    period: 'One-Time',
    description: '30 Day Builder Access',
    features: [
      'Live Support',
      'One Checkout Page (Secretly doesn’t go live)',
    ],
    cta: 'Try for $9',
    popular: false,
    color: 'from-blue-500 to-blue-600',
  },
  {
    name: 'Pro',
    price: '$129',
    period: '/month or $79/m billed annually',
    description: 'Most popular for growing brands',
    features: [
      '5 Designed Checkouts (They go live lol)',
      'Unlimited Products',
      'A/B Split Testing',
      'Advanced Analytics including G-Analytics & Microsoft Clarity',
      'Priority Support',
      'Advanced Builder',
      'Custom CSS',
      'DFY Bonus Templates',
    ],
    cta: 'Upgrade to Pro',
    popular: true,
    color: 'from-green-500 to-green-600',
  },
  {
    name: 'DFY',
    price: '$499 One-Time',
    period: '+ $79/m or Free w/ $948/y',
    description: 'We build and optimize it for you',
    features: [
      'CRO Service',
      'We build it & integrate it',
      'Unlimited Revisions',
      'Satisfaction Guarantee',
    ],
    cta: 'Done-For-You Setup',
    popular: false,
    color: 'from-purple-500 to-purple-600',
  },
  {
    name: 'Enterprise',
    price: 'From $399',
    period: '/month',
    description: 'Custom solutions & VIP treatment',
    features: [
      'Dedicated Success Manager',
      'Whitelabeling & Reselling',
      'Custom Integrations',
      'Slack Support (VIP Level)',
      'Unlimited Checkouts & Accounts',
    ],
    cta: 'Talk to Sales',
    popular: false,
    color: 'from-gray-700 to-gray-800',
  },
];
